import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Navebar from './../components/Navebar';
import requests from '../utils/requests'
import Result from './../components/Result';

export default function Home({data}) {
  console.log('This is data',data.results)
  return (
    <div >
      <Head>
        <title>Hulu 3.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header  */}
      <Header/>
      

      {/* Navebar */}

      <Navebar/>

      {/* results */}

      <Result result={data.results} />
      
      

     

     
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre=context.query.genre
  // Fetch data from external API
  const res = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}